add_executable(pitaya_tests 
    pitaya_test.cpp
    elapsed_timer_test.cpp
    interval_timer_test.cpp
    lookup_table_1d_test.cpp
    lookup_table_2d_test.cpp
    boolean_debouncer_test.cpp
    edge_detector_test.cpp
    on_delay_test.cpp
    off_delay_test.cpp
    on_off_delay_test.cpp
    limit_test.cpp
    hysteresis_limiter_test.cpp
    linear_ramp_test.cpp
    rate_of_change_limiter_test.cpp
    threshold_protection_test.cpp
    derivative_test.cpp
    integrator_test.cpp
    first_order_low_pass_filter_test.cpp
    second_order_filter_test.cpp
    hardware_filter_compensator_test.cpp
    pi_controller_test.cpp
    sogi_filter_test.cpp
    sogi_filter_sequence_extractor_test.cpp
)
target_link_libraries(pitaya_tests PRIVATE pitaya::pitaya GTest::gtest_main)

include(GoogleTest)
gtest_discover_tests(pitaya_tests)
